base: configs/evaluating_netgo-v1/metafile.yml
task: cellular_component
num_classes: 2880
msa_max_size: -1
max_len: 2048
top_k: 64
netD: timm_swinv2_base_window16
trained_model: ema-fmax-highest-rank1.pth,ema-fmax-highest-rank2.pth,ema-fmax-highest-rank3.pth,ema-fmax-highest-rank4.pth,ema-fmax-highest-rank5.pth
batch_size: 8
no_eval: false
torch_compile: false
prediction_save: /data0/Databases/GOA-S2F/data-netgo/target/pred_seqs/ng-v1-25-04-02/cc/ema-avgfmax-highest-rank123.npy