base: configs/evaluating_msa-v1/metafile.yml
task: molecular_function
num_classes: 7038
netD: timm_tresnet_m
trained_model: ema-fmax-highest.pth
no_eval: false
prediction_save: /root/autodl-tmp/rogo/data/target/pred_seqs/msa-v1-5-5/mfo/ema-fmax-highest-a5.npy