base: configs/training_netgo-v1/metafile.yml
task: biological_process
num_classes: 21814
dataloader_num_workers: 20
msa_max_size: -1
top_k: 64
max_len: 2048
# netD: timm_ecaresnetblur101d
# netD: timm_vit_base_patch16
netD: timm_naflexvit_base_patch16
# optim: AdamW
optim: Lamb
optim_eps: 1.e-6
epochs: 400
stop_epoch: 400
# lr: 0.003
lr: 0.003
lr_policy: cycle
lr_pct_start: 0.1
lr_cycle_three_phase: false
# initial = lr / div_factor (25 default); min_lr = initial / final_div_factor
lr_final_div_factor: 120
batch_size: 40
# gpu_ids:
#   - 0
#   - 1
#   - 2
#   - 3
validation_split: 0.
extra_val: valid
no_amp: false
smoothing: 0.
torch_compile: false
weight_decay: 0.05
no_model_weight_decay: true
ema_decay: 0.9997
mixup_alpha: 0.2
accum_steps: 1
top_k_models: 5
wandb: profun-som-v6