base: configs/training_netgo-v1/metafile.yml
task: cellular_component
num_classes: 2880
dataloader_num_workers: 15
msa_max_size: -1
netD: timm_ecaresnet101d
optim: AMSGrad
epochs: 140
stop_epoch: 60
lr: 0.0002
lr_policy: cycle
pct_start: 0.1
batch_size: 32
gpu_ids:
  - 0
validation_split: 0.
extra_val: valid
smoothing: 0.
torch_compile: true
weight_decay: 1e-5
wandb: profun-som-v3